require(knitr)
require(markdown)
setwd("C:\\ting\\coursea\\getting_cleaning_data\\project\\GettingAndCleaningData-master\\GettingAndCleaningData-master\\Project")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")